export const PROVINCE_REQUEST = 'PROVINCE_REQUEST';
export const PROVINCE_SUCCESS = 'PROVINCE_SUCCESS';
export const PROVINCE_FAIL = 'PROVINCE_FAIL';

export const DISTRICT_REQUEST = 'DISTRICT_REQUEST';
export const DISTRICT_SUCCESS = 'DISTRICT_SUCCESS';
export const DISTRICT_FAIL = 'DISTRICT_FAIL';

export const WARD_REQUEST = 'WARD_REQUEST';
export const WARD_SUCCESS = 'WARD_SUCCESS';
export const WARD_FAIL = 'WARD_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';