export const REGISTER_SELLER_REQUEST = 'REGISTER_SELLER'
export const REGISTER_SELLER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_SELLER_FAIL = 'REGISTER_SELLER_FAIL'

export const MAKE_APPOINTMENT_REQUEST = 'MAKE_APPOINTMENT_REQUEST';
export const MAKE_APPOINTMENT_SUCCESS = 'MAKE_APPOINTMENT_SUCCESS';
export const MAKE_APPOINTMENT_FAIL = 'MAKE_APPOINTMENT_FAIL';

export const USER_ALL_APPOINTMENT_REQUEST = 'USER_ALL_APPOINTMENT_REQUEST';
export const USER_ALL_APPOINTMENT_SUCCESS = 'USER_ALL_APPOINTMENT_SUCCESS';
export const USER_ALL_APPOINTMENT_FAIL = 'USER_ALL_APPOINTMENT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS'