const authRoutes = {
    login: '/auth/login',
    signup: '/auth/signup',
    authosignup: '/auth/signup/otp',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotpassword: '/auth/forgotpassword',
    OTPforgotpassword: '/auth/forgotpassword/otp',
    profile: '/profile',
    appointment: '/user/appointment',
    updateAppointmentLink: (id) => `/user/appointment/${id}`,
    allappointmentsuser: '/user/allappointments',
    paymentSuccess: '/payment/success',
    paymentError: '/payment/error',
    appointments: '/admin/appointments',
    payments: '/admin/payments',
    getUser: '/admin/list_user/:id',
    getUserLink: (id) => `/admin/list_user/${id}`,
    getUserAppointments: '/admin/appointment_user/:id',
    getUserAppointmentsLink: (id) => `/admin/appointment_user/${id}`,
    getUserPayment: '/admin/payment_user/:id',
    getUserpaymentLink: (id) => `/admin/payment_user/${id}`,
};
export default authRoutes;
